name: azan_watch_app
description: "Azan Watch App - Prayer Times & Qibla Direction"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  geolocator: ^11.0.1
  flutter_local_notifications: ^16.3.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  percent_indicator: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
